# Generators are registered within seed.yml, once their tests are passing
name: Publish @fern-api/python-v2-codegen

on:
  push:
    branches:
      # - main
      - vargas/publish-python2
    # paths:
    #   - "generators/python-v2/codegen/versions.yml"
  # workflow_dispatch:
  #   inputs:
  #     version:
  #       description: "The version of the generator to publish."
  #       required: true
  #       type: string

env:
  PACKAGE_NAME: "@fern-api/python-v2-codegen"
  GITHUB_TOKEN: ${{ secrets.FERN_GITHUB_TOKEN }}
  NPM_TOKEN: ${{ secrets.FERN_NPM_TOKEN }}

jobs:
  publish:
    if: ${{ github.event_name == 'push' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo at current ref
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 2

      - name: Install
        uses: ./.github/actions/install

      - name: 🧪 Build
        run: pnpm --filter=${{ env.PACKAGE_NAME }} compile

      - name: 🧪 Test
        run: pnpm --filter=${{ env.PACKAGE_NAME }} test

      # TODO: The filter didn't work here, so we're just running the command directly
      # pnpm --filter=${{ env.PACKAGE_NAME }} dist 0.0.1
      # Commend "dist" not found ???
      # pnpm dist 0.0.1
      - name: Run publish
        run: |
          cd generators/python-v2/codegen
          npm run dist
          cd dist
          echo "//registry.npmjs.org/:_authToken=${{ env.NPM_TOKEN }}" > ~/.npmrc
          npm publish --access public

  