# TODO: delete this when we migrate to the one versions file in `publish-generators-v2`
name: publish-generators (hackweek)

on:
  push:
    branches:
      - dsinghvi/full-hackweek

env:
  DOCKER_BUILDKIT: 1

jobs:
  ts-node-sdk:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install
        uses: ./.github/actions/install

      - name: Print Version
        run: |
          echo "VERSION=$projectVersion" >> "0.0.0-hw0"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: fernapi
          password: ${{ secrets.FERN_API_DOCKERHUB_PASSWORD }}

      - name: Publish fernapi/fern-typescript-node-sdk docker
        run: |
          pnpm --filter @fern-typescript/sdk-generator-cli dockerTagVersion:node "$VERSION"
          docker push fernapi/fern-typescript-node-sdk:"$VERSION"
